// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_duration();
RcppExport SEXP _rcpp_module_boot_test();
RcppExport SEXP _rcpp_module_boot_time();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_duration", (DL_FUNC) &_rcpp_module_boot_duration, 0},
    {"_rcpp_module_boot_test", (DL_FUNC) &_rcpp_module_boot_test, 0},
    {"_rcpp_module_boot_time", (DL_FUNC) &_rcpp_module_boot_time, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_fm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
