// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.6.1
// source: AntMetadata.proto

package fort_myrmidon_pb

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AntStaticValue_Type int32

const (
	AntStaticValue_BOOL   AntStaticValue_Type = 0
	AntStaticValue_INT    AntStaticValue_Type = 1
	AntStaticValue_DOUBLE AntStaticValue_Type = 2
	AntStaticValue_STRING AntStaticValue_Type = 3
	AntStaticValue_TIME   AntStaticValue_Type = 4
)

// Enum value maps for AntStaticValue_Type.
var (
	AntStaticValue_Type_name = map[int32]string{
		0: "BOOL",
		1: "INT",
		2: "DOUBLE",
		3: "STRING",
		4: "TIME",
	}
	AntStaticValue_Type_value = map[string]int32{
		"BOOL":   0,
		"INT":    1,
		"DOUBLE": 2,
		"STRING": 3,
		"TIME":   4,
	}
)

func (x AntStaticValue_Type) Enum() *AntStaticValue_Type {
	p := new(AntStaticValue_Type)
	*p = x
	return p
}

func (x AntStaticValue_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AntStaticValue_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_AntMetadata_proto_enumTypes[0].Descriptor()
}

func (AntStaticValue_Type) Type() protoreflect.EnumType {
	return &file_AntMetadata_proto_enumTypes[0]
}

func (x AntStaticValue_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AntStaticValue_Type.Descriptor instead.
func (AntStaticValue_Type) EnumDescriptor() ([]byte, []int) {
	return file_AntMetadata_proto_rawDescGZIP(), []int{0, 0}
}

type AntStaticValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        AntStaticValue_Type  `protobuf:"varint,1,opt,name=type,proto3,enum=fort.myrmidon.pb.AntStaticValue_Type" json:"type,omitempty"`
	BoolValue   bool                 `protobuf:"varint,2,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	IntValue    int32                `protobuf:"varint,3,opt,name=intValue,proto3" json:"intValue,omitempty"`
	DoubleValue float64              `protobuf:"fixed64,4,opt,name=doubleValue,proto3" json:"doubleValue,omitempty"`
	StringValue string               `protobuf:"bytes,5,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	TimeValue   *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timeValue,proto3" json:"timeValue,omitempty"`
}

func (x *AntStaticValue) Reset() {
	*x = AntStaticValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AntMetadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AntStaticValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntStaticValue) ProtoMessage() {}

func (x *AntStaticValue) ProtoReflect() protoreflect.Message {
	mi := &file_AntMetadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntStaticValue.ProtoReflect.Descriptor instead.
func (*AntStaticValue) Descriptor() ([]byte, []int) {
	return file_AntMetadata_proto_rawDescGZIP(), []int{0}
}

func (x *AntStaticValue) GetType() AntStaticValue_Type {
	if x != nil {
		return x.Type
	}
	return AntStaticValue_BOOL
}

func (x *AntStaticValue) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *AntStaticValue) GetIntValue() int32 {
	if x != nil {
		return x.IntValue
	}
	return 0
}

func (x *AntStaticValue) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *AntStaticValue) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *AntStaticValue) GetTimeValue() *timestamp.Timestamp {
	if x != nil {
		return x.TimeValue
	}
	return nil
}

type AntMetadataColumn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Defaultvalue *AntStaticValue `protobuf:"bytes,2,opt,name=defaultvalue,proto3" json:"defaultvalue,omitempty"`
}

func (x *AntMetadataColumn) Reset() {
	*x = AntMetadataColumn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AntMetadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AntMetadataColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntMetadataColumn) ProtoMessage() {}

func (x *AntMetadataColumn) ProtoReflect() protoreflect.Message {
	mi := &file_AntMetadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntMetadataColumn.ProtoReflect.Descriptor instead.
func (*AntMetadataColumn) Descriptor() ([]byte, []int) {
	return file_AntMetadata_proto_rawDescGZIP(), []int{1}
}

func (x *AntMetadataColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AntMetadataColumn) GetDefaultvalue() *AntStaticValue {
	if x != nil {
		return x.Defaultvalue
	}
	return nil
}

var File_AntMetadata_proto protoreflect.FileDescriptor

var file_AntMetadata_proto_rawDesc = []byte{
	0x0a, 0x11, 0x41, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x6d, 0x79, 0x72, 0x6d, 0x69, 0x64,
	0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x02, 0x0a, 0x0e, 0x41, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x6d,
	0x79, 0x72, 0x6d, 0x69, 0x64, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3b, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c,
	0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12,
	0x08, 0x0a, 0x04, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x04, 0x22, 0x6d, 0x0a, 0x11, 0x41, 0x6e, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x44, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x2e,
	0x6d, 0x79, 0x72, 0x6d, 0x69, 0x64, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AntMetadata_proto_rawDescOnce sync.Once
	file_AntMetadata_proto_rawDescData = file_AntMetadata_proto_rawDesc
)

func file_AntMetadata_proto_rawDescGZIP() []byte {
	file_AntMetadata_proto_rawDescOnce.Do(func() {
		file_AntMetadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_AntMetadata_proto_rawDescData)
	})
	return file_AntMetadata_proto_rawDescData
}

var file_AntMetadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AntMetadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_AntMetadata_proto_goTypes = []interface{}{
	(AntStaticValue_Type)(0),    // 0: fort.myrmidon.pb.AntStaticValue.Type
	(*AntStaticValue)(nil),      // 1: fort.myrmidon.pb.AntStaticValue
	(*AntMetadataColumn)(nil),   // 2: fort.myrmidon.pb.AntMetadataColumn
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_AntMetadata_proto_depIdxs = []int32{
	0, // 0: fort.myrmidon.pb.AntStaticValue.type:type_name -> fort.myrmidon.pb.AntStaticValue.Type
	3, // 1: fort.myrmidon.pb.AntStaticValue.timeValue:type_name -> google.protobuf.Timestamp
	1, // 2: fort.myrmidon.pb.AntMetadataColumn.defaultvalue:type_name -> fort.myrmidon.pb.AntStaticValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_AntMetadata_proto_init() }
func file_AntMetadata_proto_init() {
	if File_AntMetadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AntMetadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AntStaticValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AntMetadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AntMetadataColumn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AntMetadata_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AntMetadata_proto_goTypes,
		DependencyIndexes: file_AntMetadata_proto_depIdxs,
		EnumInfos:         file_AntMetadata_proto_enumTypes,
		MessageInfos:      file_AntMetadata_proto_msgTypes,
	}.Build()
	File_AntMetadata_proto = out.File
	file_AntMetadata_proto_rawDesc = nil
	file_AntMetadata_proto_goTypes = nil
	file_AntMetadata_proto_depIdxs = nil
}
