// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.6.1
// source: TagCloseUpCache.proto

package fort_myrmidon_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TagCloseUpCacheHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Threshold uint32    `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Family    TagFamily `protobuf:"varint,2,opt,name=family,proto3,enum=fort.myrmidon.pb.TagFamily" json:"family,omitempty"`
}

func (x *TagCloseUpCacheHeader) Reset() {
	*x = TagCloseUpCacheHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TagCloseUpCache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagCloseUpCacheHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagCloseUpCacheHeader) ProtoMessage() {}

func (x *TagCloseUpCacheHeader) ProtoReflect() protoreflect.Message {
	mi := &file_TagCloseUpCache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagCloseUpCacheHeader.ProtoReflect.Descriptor instead.
func (*TagCloseUpCacheHeader) Descriptor() ([]byte, []int) {
	return file_TagCloseUpCache_proto_rawDescGZIP(), []int{0}
}

func (x *TagCloseUpCacheHeader) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *TagCloseUpCacheHeader) GetFamily() TagFamily {
	if x != nil {
		return x.Family
	}
	return TagFamily_UNSET
}

type TagCloseUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position  *Vector2D   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Angle     float64     `protobuf:"fixed64,2,opt,name=angle,proto3" json:"angle,omitempty"`
	Value     uint32      `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Corners   []*Vector2D `protobuf:"bytes,4,rep,name=corners,proto3" json:"corners,omitempty"`
	Frameid   uint64      `protobuf:"varint,5,opt,name=frameid,proto3" json:"frameid,omitempty"`
	Imagepath string      `protobuf:"bytes,6,opt,name=imagepath,proto3" json:"imagepath,omitempty"`
}

func (x *TagCloseUp) Reset() {
	*x = TagCloseUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TagCloseUpCache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagCloseUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagCloseUp) ProtoMessage() {}

func (x *TagCloseUp) ProtoReflect() protoreflect.Message {
	mi := &file_TagCloseUpCache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagCloseUp.ProtoReflect.Descriptor instead.
func (*TagCloseUp) Descriptor() ([]byte, []int) {
	return file_TagCloseUpCache_proto_rawDescGZIP(), []int{1}
}

func (x *TagCloseUp) GetPosition() *Vector2D {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *TagCloseUp) GetAngle() float64 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *TagCloseUp) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TagCloseUp) GetCorners() []*Vector2D {
	if x != nil {
		return x.Corners
	}
	return nil
}

func (x *TagCloseUp) GetFrameid() uint64 {
	if x != nil {
		return x.Frameid
	}
	return 0
}

func (x *TagCloseUp) GetImagepath() string {
	if x != nil {
		return x.Imagepath
	}
	return ""
}

var File_TagCloseUpCache_proto protoreflect.FileDescriptor

var file_TagCloseUpCache_proto_rawDesc = []byte{
	0x0a, 0x15, 0x54, 0x61, 0x67, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x55, 0x70, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x6d, 0x79,
	0x72, 0x6d, 0x69, 0x64, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x1a, 0x0e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x32, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x54, 0x61, 0x67, 0x46, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x15, 0x54, 0x61,
	0x67, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x55, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c,
	0x64, 0x12, 0x33, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x6d, 0x79, 0x72, 0x6d, 0x69, 0x64, 0x6f,
	0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x67, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x06,
	0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x22, 0xde, 0x01, 0x0a, 0x0a, 0x54, 0x61, 0x67, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x55, 0x70, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x6d,
	0x79, 0x72, 0x6d, 0x69, 0x64, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x32, 0x64, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x61, 0x6e,
	0x67, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x6f, 0x72,
	0x6e, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x6f, 0x72,
	0x74, 0x2e, 0x6d, 0x79, 0x72, 0x6d, 0x69, 0x64, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x32, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x70, 0x61, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TagCloseUpCache_proto_rawDescOnce sync.Once
	file_TagCloseUpCache_proto_rawDescData = file_TagCloseUpCache_proto_rawDesc
)

func file_TagCloseUpCache_proto_rawDescGZIP() []byte {
	file_TagCloseUpCache_proto_rawDescOnce.Do(func() {
		file_TagCloseUpCache_proto_rawDescData = protoimpl.X.CompressGZIP(file_TagCloseUpCache_proto_rawDescData)
	})
	return file_TagCloseUpCache_proto_rawDescData
}

var file_TagCloseUpCache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_TagCloseUpCache_proto_goTypes = []interface{}{
	(*TagCloseUpCacheHeader)(nil), // 0: fort.myrmidon.pb.TagCloseUpCacheHeader
	(*TagCloseUp)(nil),            // 1: fort.myrmidon.pb.TagCloseUp
	(TagFamily)(0),                // 2: fort.myrmidon.pb.TagFamily
	(*Vector2D)(nil),              // 3: fort.myrmidon.pb.Vector2d
}
var file_TagCloseUpCache_proto_depIdxs = []int32{
	2, // 0: fort.myrmidon.pb.TagCloseUpCacheHeader.family:type_name -> fort.myrmidon.pb.TagFamily
	3, // 1: fort.myrmidon.pb.TagCloseUp.position:type_name -> fort.myrmidon.pb.Vector2d
	3, // 2: fort.myrmidon.pb.TagCloseUp.corners:type_name -> fort.myrmidon.pb.Vector2d
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_TagCloseUpCache_proto_init() }
func file_TagCloseUpCache_proto_init() {
	if File_TagCloseUpCache_proto != nil {
		return
	}
	file_Vector2d_proto_init()
	file_TagFamily_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_TagCloseUpCache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagCloseUpCacheHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TagCloseUpCache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagCloseUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TagCloseUpCache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TagCloseUpCache_proto_goTypes,
		DependencyIndexes: file_TagCloseUpCache_proto_depIdxs,
		MessageInfos:      file_TagCloseUpCache_proto_msgTypes,
	}.Build()
	File_TagCloseUpCache_proto = out.File
	file_TagCloseUpCache_proto_rawDesc = nil
	file_TagCloseUpCache_proto_goTypes = nil
	file_TagCloseUpCache_proto_depIdxs = nil
}
