Document: fort-studio
Title: Debian fort-studio Manual
Author: <insert document author here>
Abstract: This manual describes what fort-studio is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fort-studio/fort-studio.sgml.gz

Format: postscript
Files: /usr/share/doc/fort-studio/fort-studio.ps.gz

Format: text
Files: /usr/share/doc/fort-studio/fort-studio.text.gz

Format: HTML
Index: /usr/share/doc/fort-studio/html/index.html
Files: /usr/share/doc/fort-studio/html/*.html
