name: build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run-tests-and-coverage:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2.0.0
        - name: Install dependencies
          run: sudo apt install build-essential git cmake libopencv-dev libasio-dev libboost-dev libgoogle-glog-dev libyaml-cpp-dev qtbase5-dev libqt5charts5-dev libeigen3-dev libprotobuf-dev protobuf-compiler lcov
        - name: Uses ccache
          uses: hendrikmuhs/ccache-action@v1
        - name: Configure
          run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_STUDIO=On -DENABLE_COVERAGE=On
        - name: Build
          working-directory: ${{github.workspace}}/build
          run: make all
        - name: Test
          uses: GabrielBB/xvfb-action@v1
          with:
            run: make coverage
            working-directory: ${{github.workspace}}/build
        - name: Sends coverage
          uses: coverallsapp/github-action@v1.1.2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: ${{github.workspace}}/build/coverage/lcov.info
            base-path: ${{github.workspace}}
